data_class: Yahoo
max_workers: 1
csv: Yahoo
period: daily
db_tables:
    db_stock_info:
        disabled: 1
        drop_table: 1
        table_name: stock_info
    db_stock_monthly:
        disabled: 1
        drop_table: 1
        table_name: stock_monthly
        date_range:
            start_date: 2000-01-01
            end_date: 2023-10-10
            today_as_end_date: 1
            recent_day: 0
    db_stock_weekly:
        disabled: 1
        drop_table: 1
        table_name: stock_weekly
        date_range:
            start_date: 2010-01-01
            end_date: 2023-10-10
            today_as_end_date: 1
            recent_day: 0
    db_stock_daily:
        disabled: 0
        drop_table: 1
        table_name: stock_daily
        date_range:
            start_date: 2020-01-01
            end_date: 2023-10-10
            today_as_end_date: 1
            recent_day: 720
    db_stock_120:
        disabled: 1
        drop_table: 0
        table_name: stock_120_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_60:
        disabled: 1
        drop_table: 0
        table_name: stock_60_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_30:
        disabled: 1
        drop_table: 0
        table_name: stock_30_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_15:
        disabled: 1
        drop_table: 0
        table_name: stock_15_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_5:
        disabled: 1
        drop_table: 0
        table_name: stock_5_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_1:
        disabled: 1
        drop_table: 0
        table_name: stock_1_minute
        date_range:
            start_date: 2023-01-01 09:30:00
            end_date: 2023-09-28 09:30:00
            today_as_end_date: 1
            recent_day: 0