# 数据源类， 如果要接入其他数据源， 请实现interfaces/DataApi.py下的接口, 已支持的有AkShare, Yahoo
data_class: AkShare
# 下载线程数
max_workers: 5
# 选股模式, 使用db_tables下的其中一类做为选股配置， 可选db_stock_daily, db_stock_{1, 5, 15, 30, 60, 120}_minute
mode: db_stock_daily
db_tables:
    # 股票信息表
    db_stock_info:
        # 是否禁用， 禁用后执行db_mian.py不下载该表的数据
        disabled: 0
        # 1删除表重新下载 | 0不删除表中已有数据，从最近时间更新数据
        drop_table: 1
        table_name: stock_info
    # 股票日历史数据表
    db_stock_daily:
        # 是否禁用， 禁用后执行db_mian.py不下载该表的数据
        disabled: 0
        drop_table: 1
        table_name: stock_daily
        date_range:
            start_date: 2020-01-01
            end_date: 2023-10-01
            # 使用今天做为结束时间
            today_as_end_date: 1
            # 下载最近N天的数据, 包含星期天节假日， 请自行计算星期天节假日
            recent_day: 0
    # 股票120分钟历史数据表
    db_stock_120_minute:
        disabled: 0
        drop_table: 1
        table_name: stock_120_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
      # 股票60分钟历史数据表
    db_stock_60_minute:
        disabled: 0
        drop_table: 1
        table_name: stock_60_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_30_minute:
        disabled: 0
        drop_table: 1
        table_name: stock_30_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_15_minute:
        disabled: 0
        drop_table: 1
        table_name: stock_15_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_5_minute:
        disabled: 0
        drop_table: 1
        table_name: stock_5_minute
        date_range:
            start_date: 2023-01-01 00:00:00
            end_date: 2023-10-01 15:00:00
            today_as_end_date: 1
            recent_day: 0
    db_stock_1_minute:
        disabled: 0
        drop_table: 1
        table_name: stock_1_minute
        date_range:
            start_date: 2023-01-01 09:30:00
            end_date: 2023-09-28 09:30:00
            today_as_end_date: 1
            recent_day: 0